"""Constants for the standalone HO-SC-8W irrigation integration."""

DOMAIN = "nikas_ho_sc_8w"

INTEGRATION_NAME = "NikaS HO-SC-8W Irrigation"
MANUFACTURER = "INKBIRD / HiOazo"
MODEL = "HO-SC-8W"
NUM_ZONES = 8
NUM_PRODUCTION_ZONES = 8
TUYA_VERSION = 3.3

MANUAL_DURATION_MIN = 1
MANUAL_DURATION_MAX = 120
SEASONAL_ADJUST_MIN = -90
SEASONAL_ADJUST_MAX = 100
SEASONAL_ADJUST_STEP = 10
ZONE8_DP38_WRITES_ENABLED = False
ZONE8_DP38_HEX_PROBE_ENABLED = True
ZONE8_KNOWN_RESTORE_ENABLED = False
ZONE8_ANCHOR_DATE_TEST_ENABLED = False
ZONE8_MASK_WRITE_TEST_ENABLED = True
ZONE8_DAMAGED_BLOCK_HEX = "08EFEFEFEFEFEFFF8A9FDFEFFBFF007F1A090311"
ZONE8_KNOWN_BACKUP_HEX = "0800FFFFFFFFFFFFFFFFFFFFFFFF03011A090311"
ZONE8_KNOWN_RESTORE_CONFIRMATION = "RESTORE_ZONE8_KNOWN_BACKUP"
ZONE8_ANCHOR_DATE_TEST_TARGET_HEX = "0800FFFFFFFFFFFFFFFFFFFFFFFF03011A090211"
ZONE8_ANCHOR_DATE_TEST_CONFIRMATION = "WRITE_ZONE8_ANCHOR_DATE_2026_09_02_ONCE"
ZONE8_MASK_WRITE_TEST_CURRENT_READ_HEX = "0800FFFFFFFFFFFFFFFFFFFFFFFF03011A090411"
ZONE8_MASK_WRITE_TEST_PAYLOAD_HEX = "8000FFFFFFFFFFFFFFFFFFFFFFFF03011A090511"
ZONE8_MASK_WRITE_TEST_EXPECTED_READ_HEX = "0800FFFFFFFFFFFFFFFFFFFFFFFF03011A090511"
ZONE8_MASK_WRITE_TEST_CONFIRMATION = "WRITE_DP38_ZONE8_MASK_80_DATE_2026_09_05_ONCE"
DP38_KNOWN_BACKUP_HEX_BY_ZONE = {
    1: "010A05FFFFFFFFFF00FFFFFFFFFF03021A071311",
    2: "021405FFFFFFFFFF00FFFFFFFFFF03011A071311",
    3: "030A05FFFFFFFFFF0AFFFFFFFFFF03021A071311",
    4: "040A05FFFFFFFFFF00FFFFFFFFFF03021A071311",
    5: "050710FFFFFFFFFF0AFFFFFFFFFF03021A071311",
    6: "06140B0D11FFFFFF000000FFFFFF03011A071810",
    7: "0700FFFFFFFFFFFFFFFFFFFFFFFF007F1A081311",
    8: ZONE8_KNOWN_BACKUP_HEX,
}

SERVICE_START_MANUAL_QUEUE = "start_manual_queue"
SERVICE_SKIP_CURRENT_MANUAL = "skip_current_manual"
SERVICE_STOP_MANUAL = "stop_manual"
SERVICE_RESUME_AUTOMATIC = "resume_automatic"
SERVICE_SET_SEASONAL_ADJUSTMENT = "set_seasonal_adjustment"
SERVICE_SET_ZONE8_SCHEDULE_FIELD = "set_zone8_schedule_field"
SERVICE_RESTORE_ZONE8_SCHEDULE = "restore_zone8_schedule"
SERVICE_PROBE_ZONE8_DP38_HEX = "probe_zone8_dp38_hex"
SERVICE_CAPTURE_DP38_SNAPSHOT = "capture_dp38_snapshot"
SERVICE_RESTORE_ZONE8_KNOWN_BACKUP = "restore_zone8_known_backup"
SERVICE_TEST_ZONE8_ANCHOR_DATE_WRITE = "test_zone8_anchor_date_write"
SERVICE_TEST_ZONE8_MASK_WRITE = "test_zone8_mask_write"

ATTR_CONFIG_ENTRY_ID = "config_entry_id"
ATTR_ZONES = "zones"
ATTR_ZONE = "zone"
ATTR_DURATION_MINUTES = "duration_minutes"
ATTR_VALUE = "value"
ATTR_FIELD = "field"
ATTR_CONFIRMATION = "confirmation"
ATTR_PHASE = "phase"

DP38_SNAPSHOT_CONFIRMATION = "DP38_FULL_SNAPSHOT_READ_ONLY"

DP_NORMAL_TIME = 38
DP_IRRIGATION_MODE = 44
DP_IRRIGATION_TIME_ALL = 45
DP_OPERATION_MODE = 101
DP_RAIN_SENSOR = 102
DP_SEASONAL_ADJUST = 103
DP_MERGE_HISTORY = 104
DP_RESET_DEVICE = 105
DP_TIMEERROR_ALARM = 106
DP_ACTIVE_ZONE = 107
DP_QUEUED_ZONE = 108
DP_CANCEL_ALARM_VOICE = 109

CONF_DEVICE_ID = "device_id"
CONF_LOCAL_KEY = "local_key"
CONF_DEVICE_IP = "device_ip"
CONF_DEVICE_NAME = "device_name"
CONF_CONNECTION_MODE = "connection_mode"
CONF_CLOUD_API_KEY = "cloud_api_key"
CONF_CLOUD_API_SECRET = "cloud_api_secret"
CONF_CLOUD_API_REGION = "cloud_api_region"

CONNECTION_MODE_AUTO = "auto"
CONNECTION_MODE_LOCAL = "local"
CONNECTION_MODE_CLOUD = "cloud"
CONNECTION_MODES = frozenset(
    {CONNECTION_MODE_AUTO, CONNECTION_MODE_LOCAL, CONNECTION_MODE_CLOUD}
)

PANEL_TITLE = "Автополив"
PANEL_ICON = "mdi:sprinkler"
PANEL_URL_PATH = "dashboard-irrigation"
PANEL_PARENT_PATH = "/dashboard-actions/home"
PANEL_ELEMENT_NAME = "nikas-ho-sc-8w-panel"
PANEL_VERSION = "0.6.59"
PANEL_STATIC_URL = "/nikas-ho-sc-8w"
PANEL_JS_URL = f"{PANEL_STATIC_URL}/irrigation-panel-v0659.mjs"
