from __future__ import annotations
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PANEL = ROOT / "custom_components/nikas_ho_sc_8w/frontend/irrigation-panel.js"
def replace_once(text, old, new, label):
    count=text.count(old)
    if count != 1: raise RuntimeError(f"{label}: expected one exact match, got {count}")
    return text.replace(old,new,1)
def regex_once(text, pattern, replacement, label):
    updated,count=re.subn(pattern,replacement,text,count=1,flags=re.S)
    if count != 1: raise RuntimeError(f"{label}: expected one regex match, got {count}")
    return updated
source=PANEL.read_text(encoding="utf-8")
source = replace_once(source, 'const UI_VERSION = "0.6.13";', 'const UI_VERSION = "0.6.14";', 'UI version')
source = replace_once(source, 'const ASSET_VERSION = "0.6.13";', 'const ASSET_VERSION = "0.6.14";', 'asset version')
source = replace_once(source, '      this._longPressHeld = false;\n      this._onRealViewportResize = () => requestAnimationFrame(() => this._clampAndApplyTransform(false));', '      this._longPressHeld = false;\n      this._refreshBusy = false;\n      this._onRealViewportResize = () => requestAnimationFrame(() => this._clampAndApplyTransform(false));', 'refresh state')
source = replace_once(source, '    header() {\n      return `<header class="appHeader">\n        <button class="headerButton menuButton" data-ha-menu aria-label="Меню Home Assistant"><ha-icon icon="mdi:menu"></ha-icon></button>\n        <div class="headerTitle"><strong>HO-SC-8W</strong><small>Система полива · UI v${UI_VERSION}</small></div>\n        <button class="headerButton refreshButton" data-refresh aria-label="Обновить"><ha-icon icon="mdi:refresh"></ha-icon></button>\n      </header>`;\n    }', '    header() {\n      return `<header class="appHeader">\n        <button class="headerButton menuButton" data-ha-menu aria-label="Меню Home Assistant"><ha-icon icon="mdi:menu"></ha-icon></button>\n        <button class="headerTitle" data-parent-navigation aria-label="Вернуться в исходную базовую панель"><strong>HO-SC-8W</strong><small>UI v${UI_VERSION}</small></button>\n        <button class="headerButton refreshButton" data-refresh aria-label="Обновить"><ha-icon icon="mdi:refresh"></ha-icon></button>\n      </header>`;\n    }', 'header plaque')
source = replace_once(source, '    openHaMenu() {\n      this.dispatchEvent(new CustomEvent("hass-toggle-menu", {\n        bubbles: true,\n        composed: true,\n      }));\n    }', '    openHaMenu() {\n      this.dispatchEvent(new CustomEvent("hass-toggle-menu", {\n        bubbles: true,\n        composed: true,\n      }));\n    }\n\n    _parentPath() {\n      const configured = this._panel?.config?.parent_path;\n      try {\n        const url = new URL(window.location.href);\n        const from = url.searchParams.get("from") || url.searchParams.get("return_to");\n        if (from?.startsWith("/dashboard-")) return from;\n      } catch (_error) {\n        // Fall through to History API state and configured parent path.\n      }\n      const stateFrom = window.history.state?.from || window.history.state?.return_to;\n      if (typeof stateFrom === "string" && stateFrom.startsWith("/dashboard-")) return stateFrom;\n      return configured || "/dashboard-actions";\n    }\n\n    goParent() {\n      const target = this._parentPath();\n      if (!target || target === window.location.pathname) return;\n      window.history.pushState(null, "", target);\n      window.dispatchEvent(new Event("location-changed"));\n    }', 'source return')
source = regex_once(source, '    async refreshNow\\(\\) \\{.*?\\n    \\}\\n\\n    entities\\(\\) \\{', '    async refreshNow() {\n      if (!this._hass?.callService || this._refreshBusy) return;\n      const button = this.shadowRoot.querySelector("[data-refresh]");\n      this._refreshBusy = true;\n      if (button) {\n        button.disabled = true;\n        button.classList.add("busy");\n      }\n      const e = this.entities();\n      const ids = [\n        e.connection, e.operation, e.irrigation, e.active, e.queued,\n        e.rain, e.pressure, e.seasonal, e.timerError, e.cache,\n        ...Object.values(e.zones).flatMap((z) => [z.remaining, z.elapsed, z.schedule]),\n      ].filter((id, index, all) => id && this.states()[id] && all.indexOf(id) === index);\n      try {\n        if (ids.length) await this._hass.callService("homeassistant", "update_entity", { entity_id: ids });\n      } catch (_err) {\n        // The panel remains factual if forced refresh is unsupported.\n      } finally {\n        this._refreshBusy = false;\n        if (button) {\n          button.disabled = false;\n          button.classList.remove("busy");\n        }\n      }\n    }\n\n    entities() {', 'refresh method')
source = replace_once(source, '    zoneIcon(zone) {\n      return ({ 1: "mdi:sprinkler", 2: "mdi:sprinkler-variant", 3: "mdi:flower", 4: "mdi:greenhouse", 5: "mdi:sprout", 6: "mdi:pine-tree" })[zone] || "mdi:water";\n    }', '    zoneType(zone) {\n      return ({ 1: "Газон", 2: "Газон", 3: "Газон", 4: "Цветник", 5: "Кусты", 6: "Теплица" })[zone] || "Зона";\n    }\n    zoneIcon(zone) {\n      return ({ 1: "mdi:grass", 2: "mdi:grass", 3: "mdi:grass", 4: "mdi:flower", 5: "mdi:sprout", 6: "mdi:greenhouse" })[zone] || "mdi:water";\n    }', 'zone semantics')
source = regex_once(source, '    zoneDetail\\(e, zone\\) \\{.*?\\n    \\}\\n    zonesView\\(e\\) \\{', '    zoneDetail(e, zone) {\n      const z = this.zoneRuntime(e, zone);\n      const a = z.attrs;\n      return `<button class="inlineBack" data-drill-back><ha-icon icon="mdi:arrow-left"></ha-icon>Зоны</button><section class="detailCard"><div class="detailHead"><span class="scene scene${zone}"><ha-icon icon="${this.zoneIcon(zone)}"></ha-icon></span><div><small>ЗОНА ${zone} · ${this.zoneType(zone).toUpperCase()}</small><h2>${this.esc(z.label)}</h2></div></div><div class="detailGrid"><div><small>Длительность</small><b>${this.esc(z.duration)} мин</b></div><div><small>Старт</small><b>${this.esc(z.start)}</b></div><div><small>Цикл</small><b>${this.esc(this.cycleText(a))}</b></div><div><small>Дождь</small><b>${a.rain_sensor_follow === true ? "Учитывать" : a.rain_sensor_follow === false ? "Игнорировать" : "—"}</b></div></div><p>Фактические параметры DP38. Редактирование и raw-write из панели отсутствуют.</p></section>`;\n    }\n    zonesView(e) {', 'zone detail')
source = regex_once(source, '    zonesView\\(e\\) \\{.*?\\n    \\}\\n    programView\\(e\\) \\{', '    zonesView(e) {\n      if (this._drillZone) return this.zoneDetail(e, this._drillZone);\n      const cards = Array.from({ length: 6 }, (_, i) => i + 1).map((zone) => {\n        const z = this.zoneRuntime(e, zone);\n        return `<button class="zoneCard ${z.tone}" data-zone="${zone}" data-entity="${this.esc(z.q.schedule)}"><span class="scene scene${zone}"><ha-icon icon="${this.zoneIcon(zone)}"></ha-icon></span><span><small>ЗОНА ${zone} · ${this.zoneType(zone).toUpperCase()}</small><b>${this.esc(z.label)}</b><em>${this.esc(z.start)} · ${this.esc(z.duration)} мин</em></span><ha-icon icon="mdi:chevron-right"></ha-icon></button>`;\n      }).join("");\n      return `<div class="pageIntro"><small>ЗОНЫ 1–6</small><h2>Рабочие зоны</h2><p>1–3 газон · 4 цветник · 5 кусты · 6 теплица.</p></div><div class="zoneCards">${cards}</div>`;\n    }\n    programView(e) {', 'zones view')
source = regex_once(source, '    programView\\(e\\) \\{.*?\\n    \\}\\n    manualView\\(e\\) \\{', '    programView(e) {\n      const seasonal = this.state(e.seasonal);\n      const rain = this.state(e.rain);\n      const zoneRows = Array.from({ length: 6 }, (_, i) => i + 1).map((zone) => {\n        const z = this.zoneRuntime(e, zone);\n        return `<button class="programRow" data-zone="${zone}" data-entity="${this.esc(z.q.schedule)}"><span>Зона ${zone} · ${this.zoneType(zone)}</span><b>${this.esc(z.start)} · ${this.esc(z.duration)} мин</b><ha-icon icon="mdi:chevron-right"></ha-icon></button>`;\n      }).join("");\n      return `<div class="pageIntro"><small>ПРОГРАММА</small><h2>Автоматический полив</h2><p>Read-only представление программы контроллера.</p></div><section class="summaryGrid"><button data-entity="${this.esc(e.operation)}"><small>Режим</small><b>${this.esc(this.human("operation", this.state(e.operation)))}</b></button><button data-entity="${this.esc(e.seasonal)}"><small>Сезон</small><b>${this.bad(seasonal) ? "Нет данных" : `${seasonal} %`}</b></button><button data-entity="${this.esc(e.rain)}"><small>Дождь</small><b>${this.esc(this.human("rain", rain))}</b></button><button data-entity="${this.esc(e.cache)}"><small>Кэш DP38</small><b>${this.esc(this.human("cache", this.state(e.cache)))}</b></button></section><section class="programList">${zoneRows}</section>`;\n    }\n    manualView(e) {', 'program view')
source = regex_once(source, '    manualView\\(e\\) \\{.*?\\n    \\}\\n    diagnosticsView\\(e\\) \\{', '    manualView(e) {\n      const zoneButtons = Array.from({ length: 6 }, (_, i) => i + 1).map((zone) => `<button class="manualZone ${this._manualZone === zone ? "active" : ""}" data-manual-zone="${zone}">${zone}<small>${this.zoneType(zone)}</small></button>`).join("");\n      return `<div class="pageIntro"><small>РУЧНОЙ ПОЛИВ</small><h2>Подготовка запуска</h2><p>Команда запуска остаётся закрытой до проверенного Actions API.</p></div><section class="manualCard"><div class="manualZones">${zoneButtons}</div><div class="stepper"><button data-duration="-1"><ha-icon icon="mdi:minus"></ha-icon></button><b>${this._manualDuration}<small> мин</small></b><button data-duration="1"><ha-icon icon="mdi:plus"></ha-icon></button></div><button class="lockedStart" disabled><ha-icon icon="mdi:lock-outline"></ha-icon>Запуск пока недоступен</button></section>`;\n    }\n    diagnosticsView(e) {', 'manual view')
source = replace_once(source, '        if (target.matches("[data-ha-menu]")) { this.openHaMenu(); return; }\n        if (target.matches("[data-refresh]")) { this.refreshNow(); return; }', '        if (target.matches("[data-ha-menu]")) { this.openHaMenu(); return; }\n        if (target.matches("[data-parent-navigation]")) { this.goParent(); return; }\n        if (target.matches("[data-refresh]")) { this.refreshNow(); return; }', 'header click')
source = replace_once(source, '        @media(max-width:520px){.headerTitle strong{font-size:21px}.headerTitle small{font-size:13px}.connectionBadge{font-size:16px}.connectionWrap>small{font-size:13px!important}}\n      `;', '        @media(max-width:520px){.headerTitle strong{font-size:21px}.headerTitle small{font-size:13px}.connectionBadge{font-size:16px}.connectionWrap>small{font-size:13px!important}}\n        /* v0.6.14: source-return Header plaque and requested zone scene mapping. */\n        .headerTitle{display:grid;place-items:center;align-content:center;width:min(100%,286px);min-height:44px;justify-self:center;padding:5px 12px;border:1px solid var(--line);border-radius:16px;background:var(--card);box-shadow:0 3px 12px #00000012;text-align:center;cursor:pointer}\n        .headerTitle strong{display:block}.headerTitle small{display:block}\n        .refreshButton.busy ha-icon{animation:nikasRefreshSpin .9s linear infinite}@keyframes nikasRefreshSpin{to{transform:rotate(360deg)}}\n        .scene1{background-image:url("${APPROVED_VISUALS.zone1}")}.scene2{background-image:url("${APPROVED_VISUALS.zone2}")}.scene3{background-image:url("${APPROVED_VISUALS.zone1}");background-position:62% center}.scene4{background-image:url("${APPROVED_VISUALS.zone3}")}.scene5{background-image:url("${APPROVED_VISUALS.zone5}")}.scene6{background-image:url("${APPROVED_VISUALS.zone4}")}\n      `;', 'css patch')
PANEL.write_text(source,encoding="utf-8")

const_path=ROOT/"custom_components/nikas_ho_sc_8w/const.py"
text=const_path.read_text(encoding="utf-8").replace('PANEL_VERSION = "0.6.13"','PANEL_VERSION = "0.6.14"')
const_path.write_text(text,encoding="utf-8")
manifest_path=ROOT/"custom_components/nikas_ho_sc_8w/manifest.json"
data=json.loads(manifest_path.read_text(encoding="utf-8")); data["version"]="1.0.0-b005.32"; manifest_path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
panel_path=ROOT/"panel.json"
data=json.loads(panel_path.read_text(encoding="utf-8")); p=data["panel"]; p["dashboard_version"]="0.6.14"; p["navigation"].update({"header_center":"source_return_plaque","header_center_action":"return_to_source_base_panel","header_center_chevron":False,"source_return_resolution":["query_from","history_state_from","parent_path"]}); p["system_visualization"]["zone_scene_thumbnails"]={"1":"lawn","2":"lawn","3":"lawn","4":"flowerbed","5":"shrubs","6":"greenhouse"}; p["standards"]["header"]="ha_menu_centered_source_return_plaque_refresh"; panel_path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
pm_path=ROOT/"panel_manifest.json"
data=json.loads(pm_path.read_text(encoding="utf-8")); data["panel_version"]="0.6.14"; data["integration_version"]="1.0.0-b005.32"; data["zone_thumbnails"]={"1":"lawn","2":"lawn","3":"lawn","4":"flowerbed","5":"shrubs","6":"greenhouse"}; pm_path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
frontend_path=ROOT/"custom_components/nikas_ho_sc_8w/frontend.py"
text=frontend_path.read_text(encoding="utf-8")
text=replace_once(text,'                "right_action": "refresh",\n                "menu_event": "hass-toggle-menu",','                "right_action": "refresh",\n                "center_action": "return_to_source_base_panel",\n                "center_style": "clickable_plaque",\n                "center_chevron": False,\n                "source_return_resolution": ["query_from", "history_state_from", "parent_path"],\n                "menu_event": "hass-toggle-menu",',"frontend header")
text=replace_once(text,'                "production_zones": [1, 2, 3, 4, 5, 6],','                "production_zones": [1, 2, 3, 4, 5, 6],\n                "zone_thumbnails": {1: "lawn", 2: "lawn", 3: "lawn", 4: "flowerbed", 5: "shrubs", 6: "greenhouse"},',"frontend zones")
frontend_path.write_text(text,encoding="utf-8")
check_path=ROOT/"scripts/check-panel-ui-v16.mjs"
text=check_path.read_text(encoding="utf-8").replace('const UI_VERSION = "0.6.13"','const UI_VERSION = "0.6.14"')
text=replace_once(text,'  \'this._showScaleToast("Масштаб 100%")\',','  \'this._showScaleToast("Масштаб 100%")\',\n  \'data-parent-navigation\',\n  \'1: "Газон", 2: "Газон", 3: "Газон", 4: "Цветник", 5: "Кусты", 6: "Теплица"\',',"check markers")
check_path.write_text(text,encoding="utf-8")
ch=ROOT/"CHANGELOG.md"; text=ch.read_text(encoding="utf-8"); marker="### Changed\n\n"; entry="- `1.0.0-b005.32` / panel `0.6.14`: apply the latest specialized-panel Header rule with a centered source-return plaque and map zone thumbnails to 1–3 lawn, 4 flowerbed, 5 shrubs and 6 greenhouse. Preserve the v1.6 stable shell, single transform viewport, DP38 read-only program and fail-closed telemetry.\n\n"; text=text if entry in text else text.replace(marker,marker+entry,1); ch.write_text(text,encoding="utf-8")
print("Applied HO-SC-8W UI 0.6.14")
